# Generated by Django 4.0.3 on 2022-03-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsite', '0002_portfolio_alter_contactusform_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusform',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='media/portfolio', verbose_name='Image'),
        ),
    ]
