# Generated by Django 4.0.3 on 2022-03-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsite', '0003_alter_contactusform_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusform',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
    ]
