# Generated by Django 4.0.3 on 2022-03-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsite', '0004_alter_contactusform_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusform',
            options={'verbose_name': 'Feedback form', 'verbose_name_plural': 'Feedback'},
        ),
    ]
