# Generated by Django 4.0.3 on 2022-03-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examsite', '0005_alter_contactusform_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusform',
            options={'verbose_name': 'Call back contact', 'verbose_name_plural': 'Call back'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
    ]
