# Generated by Django 4.0.3 on 2022-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsite', '0006_alter_contactusform_options_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio', verbose_name='Image'),
        ),
    ]
