# Generated by Django 4.0.3 on 2022-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examsite', '0007_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='media/portfolio', verbose_name='Image'),
        ),
    ]
